master_file_path: '/media/aeromec/Seagate Desktop Drive/asteroid_data/synthetic_tracklets/synthetic_image_stacks/101_snr_20_30/'
#master_file_path: '/scratch/e/emamirez/wolfesea/AsteroidImageGenerator/synthetic_tracklets/synthetic_image_stacks/500005_snr_3_20/'
train: True
num_stacks: 100
model_name: 'MCG-NJU/videomae-base'
#model_name: "google/vivit-b-16x2-kinetics400"
sample_rate: 1
fps: 2
random_sss_minsize: 256
random_sss_maxsize: 320
random_hf_p: 0.5
num_epochs: 10
batch_size: 2
remove_unused_columns: False
eval_strategy: "steps"
eval_steps: 6000
save_strategy: "steps"
save_steps: 6000
learning_rate: 0.000005
warmup_ratio: 0.1
logging_steps: 1000
load_best_model_at_end: True
metric_for_best_model: "accuracy"
push_to_hub: False
num_gpus: 4
resume_from_checkpoint: False
#resume_from_checkpoint: "/scratch/e/emamirez/wolfesea/VideoTransformer/videomae-base-finetuned-1108426/checkpoint-60000"
ignore_data_skip: True
